### ISSUE TITLE
adjust FeatureServer route urls

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-server#35]
_From @jgravois on November 11, 2014 18:17_

my recommendation is that FeatureServer urls adhere to the following convention:
http://koop.dc.esri.com/<b>rest/services</b>/github/chelm/grunt-geo/forks/FeatureServer/0

koop itself should return a valid ArcGIS Server like response for GETs/POSTs to
http://koop.dc.esri.com/rest/info
and
http://koop.dc.esri.com/rest/services (listing providers)

_Copied from original issue: chelm/koop-github#7_

**Comment by chelm** [comment]
@jgravois ahh here it is. Would mind moving this to Esri/Koop so you still own it?

**Comment by chelm** [comment]
@jgravios also can you shoot me some examples of the correct response of http://koop.dc.esri.com/rest/info and http://koop.dc.esri.com/rest/services

I know I had that at one point.
